platform: nodejs
platformVersion: "20"

run:
  port: 3000
  startCommand: node server.js

database:
  enabled: true
  engine: postgres
  mode: direct
  sourceConnectionUrl: "postgresql://embrtest:EmbrTestPass99@embr-test-pgserver.postgres.database.azure.com:5432/production_orders?sslmode=require"
  connection: production
